"""Aro contracts package exposing canonical models, enums, and state machine."""

from .enums import (
    ActionStatus,
    ActionType,
    AuditEventType,
    CaseStatus,
    ExpectedDeliveryStatus,
    Provenance,
    Role,
)
from .models import (
    Action,
    Approval,
    AuditEvent,
    Case,
    CaseBrief,
    CaseContext,
    EvidenceBundle,
    ExpectedDelivery,
    Location,
    NormalizedEvent,
    Organization,
    Policy,
    Proposal,
    RingDevice,
    RingEvent,
    User,
)
from .state_machine import (
    ALLOWED_TRANSITIONS,
    DirectExecutionWithoutApprovalError,
    InvalidStateTransitionError,
    StateMachineError,
    StateVersionMismatchError,
    TerminalStateError,
    can_transition,
    transition_case,
    validate_transition,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "Action",
    "ActionStatus",
    "ActionType",
    "Approval",
    "AuditEvent",
    "AuditEventType",
    "Case",
    "CaseBrief",
    "CaseContext",
    "CaseStatus",
    "DirectExecutionWithoutApprovalError",
    "EvidenceBundle",
    "ExpectedDelivery",
    "ExpectedDeliveryStatus",
    "InvalidStateTransitionError",
    "Location",
    "NormalizedEvent",
    "Organization",
    "Policy",
    "Proposal",
    "Provenance",
    "RingDevice",
    "RingEvent",
    "Role",
    "StateMachineError",
    "StateVersionMismatchError",
    "TerminalStateError",
    "User",
    "can_transition",
    "transition_case",
    "validate_transition",
]
