"""Repositories package for Aro persistence."""

from .errors import (
    AlreadyCompletedError,
    AlreadyExecutingError,
    ConditionalWriteFailedError,
    ConflictError,
    DuplicateRequestError,
    IdempotencyConflictError,
    NotFoundError,
    OrganizationAccessDeniedError,
    PersistenceError,
    VersionMismatchError,
)
from .in_memory import (
    InMemoryActionRepository,
    InMemoryApprovalRepository,
    InMemoryAuditRepository,
    InMemoryCaseRepository,
    InMemoryEventRepository,
    InMemoryExpectedDeliveryRepository,
    InMemoryIdempotencyRepository,
    InMemoryPolicyRepository,
)
from .interfaces import (
    ActionRepository,
    ApprovalRepository,
    AuditRepository,
    CaseRepository,
    EventRepository,
    ExpectedDeliveryRepository,
    IdempotencyRepository,
    PolicyRepository,
)

__all__ = [
    "ActionRepository",
    "AlreadyCompletedError",
    "AlreadyExecutingError",
    "ApprovalRepository",
    "AuditRepository",
    "CaseRepository",
    "ConditionalWriteFailedError",
    "ConflictError",
    "DuplicateRequestError",
    "EventRepository",
    "ExpectedDeliveryRepository",
    "IdempotencyConflictError",
    "IdempotencyRepository",
    "InMemoryActionRepository",
    "InMemoryApprovalRepository",
    "InMemoryAuditRepository",
    "InMemoryCaseRepository",
    "InMemoryEventRepository",
    "InMemoryExpectedDeliveryRepository",
    "InMemoryIdempotencyRepository",
    "InMemoryPolicyRepository",
    "NotFoundError",
    "OrganizationAccessDeniedError",
    "PersistenceError",
    "PolicyRepository",
    "VersionMismatchError",
]
